### ISSUE TITLE
Asking for help

### ISSUE THREAD

**Issue by upcwxq666** [simonepri/is-sea#3]
I am not familiar with node.js. I developed a WebGIS using C#+h5+css+JavaScript and I just want to judge a point  about whether it is in land or sea.How could I use your project ? I am looking forward for your help.Thanks so much!

**Comment by simonepri** [comment]
Have a look to the [demo](https://github.com/simonepri/is-sea/tree/master/demo).

**Comment by upcwxq666** [comment]
Thank you so much any way,I've already solved it.
